var tblExo={},tblReponses=[],tblQuestions=[],posRedim=50,qCourante=0,pCourante=0,champSaisie={},lancement=!0,modeAuteur=!1,scorm=!1,affichClavier=!1,scoreMax=0,scoreAffich=!1,tScore=0,IF_VALID="Valider",AEValeurMax=2,tempsDebut=new Date;
function afficheExo(){console.log("afficheExo");tblExo["interface"].couleur1&&useCustomColor(tblExo["interface"].couleur1);tblExo["interface"].logoaffich&&($("#logo").css("display","block"),console.log("affiche "+tblExo["interface"].logourl),console.log("affiche "+tblExo["interface"].logourl.length),1>tblExo["interface"].logourl.length?(document.getElementById("logo").src="lglg/lglg_interface/logo/UL-NOIR-WEB-h120.png",document.getElementById("logo").title="Dip - Universit\u00e9 de Lille",document.getElementById("lienLogo").href=
"http://klip.univ-lille.fr/"):(document.getElementById("logo").src=tblExo["interface"].logourl,document.getElementById("logo").title=tblExo["interface"].logotitle,document.getElementById("lienLogo").href=tblExo["interface"].logolien));$("#txtTitre").html(tblExo.titre);$("#txtSousTitre").html(tblExo.sousTitre);"0"!==tblExo.videoType&&tblExo.videoType?"1"===tblExo.videoType?$("#ctnMedia").load("lglg/lglg_medias/html5.html"):"2"===tblExo.videoType&&$("#ctnMedia").load("lglg/lglg_medias/youtube.html"):
$("#ctnMedia").load("lglg/lglg_medias/html5.html");for(var a=document.querySelector("#ctnOutils"),b=0;4>b;b++)if("--"!==tblExo.btnOutil.liste[b].fonction){var c='<a href="#" id="outil-'+tblExo.btnOutil.liste[b].fonction+'" title="'+tblExo.btnOutil.liste[b].etiquette+'"><img src="lglg/lglg_interface/images/outils/'+tblExo.btnOutil.liste[b].fonction+'.svg" alt="'+tblExo.btnOutil.liste[b].etiquette+'">';1!=tblExo.btnOutil.format&&(c+="<span>"+tblExo.btnOutil.liste[b].etiquette+"</span>");c+="</a>";$(c).appendTo(a);
$("#outil-"+tblExo.btnOutil.liste[b].fonction).click(function(a){a.preventDefault();window[this.id.substring(6)]()})}tblExo.scenario.msgAE&&$("#ctnAEAffich").load("lglg/lglg_outils/AEAffich.html");for(a=scoreMax=0;a<tblExo.pages.length;a++)for(console.log("iPage = "+a),b=0;b<tblExo.pages[a].questions.length;b++)if(console.log("iQ = "+b),tblExo.pages[a].questions[b].scoreActif&&(c=0,scoreAffich=!0,"qcm"===tblExo.pages[a].questions[b].type))for(var d=0;d<tblExo.pages[a].questions[b].propositions.length;d++)c=
parseInt(tblExo.pages[a].questions[b].propositions[d].score),0<c&&(scoreMax+=c);console.log("calcul du score max");scoreAffich&&$("#ctnScore").load("lglg/lglg_outils/scoreAffich.html");1<tblExo.pages.length&&$("#ctnNavigation").load("lglg/lglg_interface/navigQ.html");tblExo.consigne&&$("#ctnConsigne").html(tblExo.consigne);$("#ctnOutils").addClass("outilsInactif");$("#ctnOutils").hide();affichPage()}
function shadeColor(a,b){var c=parseInt(a.slice(1),16),d=0>b?0:255,e=0>b?-1*b:b,f=c>>16,g=c>>8&255,c=c&255;return"#"+(16777216+65536*(Math.round((d-f)*e)+f)+256*(Math.round((d-g)*e)+g)+(Math.round((d-c)*e)+c)).toString(16).slice(1)}
function useCustomColor(a){var b;b="#txtTitre, { color: "+a+" !important;} \n"+("#ctnTitres, #ctnOnglets, textarea:focus, .ctnQuestion { border-color: "+a+" !important;} \n")+("#ctnOnglets > div.actif { background:"+shadeColor(a,.5)+" !important; border-color: "+shadeColor(a,.5)+" !important;}\n");b=b+("#ctnOnglets > div.choisi { background: "+a+" !important; border-color: "+a+" !important;}\n")+(".navigActif:hover .st0 { fill: "+a+" !important;}");$('<style type="text/css"></style>').html(b).appendTo("head")}
function affichPage(){for(;ctnPageQ.firstChild;)ctnPageQ.removeChild(ctnPageQ.firstChild);champSaisie={};var a=document.createElement("div");a.className="txtTitrePage";a.innerHTML=tblExo.pages[pCourante].titre;ctnPageQ.appendChild(a);a=document.createElement("div");a.id="ctnQuestions";ctnPageQ.appendChild(a);for(var b=0;b<tblExo.pages[pCourante].questions.length;b++){var c=document.createElement("div");c.className="ctnQuestion";c.id="ctnQuestion_"+b;a.appendChild(c);tblQuestions[pCourante][b].affich(b)}tblReponses[pCourante].valid&&
"1"===tblExo.scenario.verrCorr?($("#nav_3").addClass("actif"),$("#nav_2").removeClass("actif"),$("#nav_2").removeClass("choisi"),validation()):($("#nav_2").addClass("actif"),$("#nav_1").hasClass("choisi")||(ongletsAffich(2),edition(),verifAccesCorr()));verifAccesCorr()}
function verifAccesCorr(){for(var a=!0,b=0;b<tblExo.pages[pCourante].questions.length;b++)if("qo"==tblExo.pages[pCourante].questions[b].type)tblReponses[pCourante].reps[b].length<tblExo.scenario.qoAccesC&&(a=!1);else if("qtrous"==tblExo.pages[pCourante].questions[b].type)for(var c=0;c<tblReponses[pCourante].reps[b].length;c++)tblReponses[pCourante].reps[b][c].length<tblExo.scenario.qoAccesC&&(a=!1);a?$("#nav_3").addClass("actif"):$("#nav_3").removeClass("actif")}
function enregistreRep(){console.log("enregistreRep");var a;a=0;if("ae"===tblExo.scenario.scormScoreRaw){for(var b=0,c=0;c<tblReponses.length;c++)for(var d=0;d<tblReponses[c].AE.length;d++)-1<tblReponses[c].AE[d]&&(b+=tblReponses[c].AE[d]),a+=1;a=parseInt(b/a*50)}else{for(c=b=0;c<tblReponses.length;c++)for(d=0;d<tblReponses[c].reps.length;d++)"qo"===tblExo.pages[c].questions[d].type&&(tblReponses[c].reps[d].length>tblExo.scenario.qoAccesC&&b++,a+=1);a=parseInt(b/a*100)}if(scorm)for(SCOSetValue("cmi.suspend_data",
JSON.stringify(tblReponses)),SCOCommit(),SCOSetValue("cmi.core.score.raw",a),SCOCommit(),b=a=0;b<tblReponses.length;b++)for(c=0;c<tblReponses[b].reps.length;c++)SCOSetValue("cmi.interactions."+a+".id","Page-"+(b+1)+"_q-"+(c+1)),SCOSetValue("cmi.interactions."+a+".student_response",tblReponses[b].reps[c]),a++;else null!=tblExo.moduleId&&localStorage.setItem(tblExo.moduleId,JSON.stringify(tblReponses))}
function validation(){tblReponses[pCourante].valid=!0;for(var a=0;a<tblQuestions[pCourante].length;a++)tblQuestions[pCourante][a].corr(a)}function edition(){$(".feedback").hide("slow");$(".QOReponse").attr("disabled",!1);$("input[type='checkbox']").attr("disabled",!1);$("input[type='checkbox']").removeClass("QCMCocheInactif");$("input[type='checkbox']").removeClass("QCMCocheBon");$("input[type='checkbox']").removeClass("QCMCocheFaux");$("#nav_2").addClass("actif")}
function lireExtraitVid(a){a=a.currentTarget.id.split("_");var b;b="c"===a[1]?"extraitCorrection":"extraitQuestion";var c=tblExo.pages[pCourante].questions[a[2]][b].debut,d=tblExo.pages[pCourante].questions[a[2]][b].fin;"vo"===a[3]!=maVideoSousTitreActif()&&(sousTitrage(!0),setTimeout(function(){window.addEventListener("click",function(){sousTitrage(!1);maVideoPause()},{capture:!0,once:!0})},2));maVideoSeek(c);maVideoPlay();var e=setInterval(function(){maVideoCurrentTime()>d&&(maVideoPause(),clearInterval(e),
sousTitrage(!1))},100)}function getSubDocument(a){if(a.contentDocument)return a.contentDocument}function svgChangeColor(){if(tblExo["interface"])for(var a=document.querySelectorAll(".svgInterface"),b=0;b<a.length;b++){var c=getSubDocument(a[b]);if(c)for(var c=c.getElementsByClassName("eltColor1"),d=0;d<c.length;d++)c[d].setAttribute("fill",tblExo["interface"].couleur1)}}
function redimCtnQuestions(){if(document.getElementById("ctnQuestions")){var a=parseInt($("#ctnQuestions").offset().top),b=$("#ctnNavigation").height(),a=window.innerHeight-(a+b+10);$("#ctnPageQ").css("max-height",a)}}
function tblReponsesInit(){console.log("tblReponsesinit "+tblExo.pages.length);for(var a=0;a<tblExo.pages.length;a++){tblReponses[a]={};tblReponses[a].valid=!1;tblReponses[a].reps=[];tblReponses[a].AE=[];tblReponses[a].score=[];for(var b=0;b<tblExo.pages[a].questions.length;b++)if(tblReponses[a].AE[b]=-1,tblReponses[a].score[b]=0,"qo"===tblExo.pages[a].questions[b].type)tblReponses[a].reps[b]="";else if("qtrous"===tblExo.pages[a].questions[b].type){tblReponses[a].reps[b]=[];for(var c=0;c<tblExo.pages[a].questions[b].txtQuestion.split(":SHORTANSWER:").length-
1;c++)tblReponses[a].reps[b][c]=""}else"qcm"===tblExo.pages[a].questions[b].type&&(tblReponses[a].reps[b]="")}sessionStorage.scorm?(scorm=!0,sessionStorage.removeItem("scorm"),SCOGetValue("cmi.suspend_data")&&(tblReponses=jQuery.parseJSON(SCOGetValue("cmi.suspend_data")))):tblExo.moduleId&&localStorage.getItem(tblExo.moduleId)&&(tblReponses=jQuery.parseJSON(localStorage.getItem(tblExo.moduleId)))}
function tblQuestionsInit(){for(var a=0;a<tblExo.pages.length;a++){tblQuestions[a]=[];for(var b=0;b<tblExo.pages[a].questions.length;b++)"qo"===tblExo.pages[a].questions[b].type?tblQuestions[a].push(Object.create(proto_qo)):"qcm"===tblExo.pages[a].questions[b].type?tblQuestions[a][b]=Object.create(proto_qcm):"qtrous"===tblExo.pages[a].questions[b].type&&(tblQuestions[a][b]=Object.create(proto_qtrous)),tblQuestions[a][b].donnees=tblExo.pages[a].questions[b]}}
function nettoieChaine(a){return a.replace(/\W/g,"").substr(0,15)};
